Update inv-transform.R (unif_binomial function)
jaidevd/statistical-computing pull request #1
Opened 2023-06-11 21:48 UTC by rohitrk06

Support for binom(n,p) is 0,1,2,...,n. Previous code does not count for this. 

Also, integer returned by cut function will not include 0, that's why subtracting 1 to shift the output by 1.

their might be some function that perform the following task without this way around. But i am new to R

2023-06-12 03:40 UTC, jaidevd requested changes
Thanks a lot for this @rohitrk06, this is perfect!

We need a CDF that contains 0 as the first element and 1 as the last element. I realized this mistake in the graded assignment but forgot to make the correction here.

The PR is fine apart from a couple of minor changes. Please make the requested changes and we'll merge this.

Thanks again,

2023-06-12 03:40 UTC, jaidevd commented on w1-pseudorandom-number-generation/inv-transform.R
> +  #return(cut(x, cdf, labels=FALSE))
Please remove the above two commented lines.

2023-06-12 03:40 UTC, jaidevd commented on w1-pseudorandom-number-generation/inv-transform.R
> +  return(cut(x, cdf, labels=FALSE)-1)
Please put spaces around the `-` sign here.

2023-06-12 14:52 UTC, rohitrk06 commented
@jaidevd, I have made required changes suggested by you. Please have a look at them

2023-06-13 04:39 UTC, merged

2023-06-13 04:39 UTC, jaidevd commented
Thanks, @rohitrk06 - keep it coming.